# Generated by Django 6.0.1 on 2026-01-15 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('Round 1', 'Round 1'), ('Round 2', 'Round 2'), ('Round 3', 'Round 3'), ('HR Round', 'HR Round'), ('Final', 'Final')], max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, help_text='Interview location or online link', max_length=200)),
                ('interviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-deadline']},
        ),
        migrations.AddField(
            model_name='application',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Application closed - no modifications allowed'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role_type': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='branches',
            field=models.CharField(blank=True, help_text='Comma separated branch names', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='posted_by',
            field=models.ForeignKey(limit_choices_to={'role_type': 'RECRUITER'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student', 'status'], name='jobs_applic_student_09cda8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='jobs_applic_job_id_a25382_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status', 'deadline'], name='jobs_jobpos_status_1400fe_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['posted_by'], name='jobs_jobpos_posted__e58aa2_idx'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='jobs.application'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='updated_by',
            field=models.ForeignKey(limit_choices_to={'role_type': 'RECRUITER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.application'),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role_type': 'RECRUITER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='applicationstatus',
            index=models.Index(fields=['application', 'timestamp'], name='jobs_applic_applica_511ef3_idx'),
        ),
    ]
