# Generated by Django 6.0.1 on 2026-01-15 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_applicationstatus_interviewschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_audience', models.CharField(choices=[('All', 'All Users'), ('Students', 'Students Only'), ('Companies', 'Companies Only')], default='All', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role_type': 'TPO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='internship_resumes/')),
                ('cover_letter', models.TextField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Applied', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role_type': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='internship_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_submission', models.TextField(blank=True, help_text='Work completed during internship')),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('recruiter_feedback', models.TextField(blank=True)),
                ('student_feedback', models.TextField(blank=True)),
                ('recruiter_rating', models.IntegerField(blank=True, choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True)),
                ('student_rating', models.IntegerField(blank=True, choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_issued_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed'), ('Completed', 'Completed')], default='In Progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='jobs.internshipapplication')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('interview_type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Phone', 'Phone')], max_length=20)),
                ('interview_link', models.URLField(blank=True, help_text='For online interviews')),
                ('location', models.CharField(blank=True, help_text='For offline interviews', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.internshipapplication')),
                ('conducted_by', models.ForeignKey(blank=True, limit_choices_to={'role_type': 'RECRUITER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='InternshipPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skills_required', models.TextField(help_text='Comma separated skills')),
                ('duration_weeks', models.IntegerField(help_text='Duration in weeks')),
                ('stipend_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved by Admin'), ('Published', 'Published'), ('Closed', 'Closed')], default='Draft', max_length=20)),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('max_backlogs', models.IntegerField(default=0)),
                ('branches', models.CharField(blank=True, help_text='Comma separated branches', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role_type': 'TPO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_internships', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(limit_choices_to={'role_type': 'RECRUITER'}, on_delete=django.db.models.deletion.CASCADE, related_name='internship_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.internshippost'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Application', 'Application'), ('Interview', 'Interview'), ('Selection', 'Selection'), ('Rejection', 'Rejection'), ('Certificate', 'Certificate'), ('Announcement', 'Announcement')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('In-App', 'In-App')], default='In-App', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone')], max_length=10)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('feedback_text', models.TextField()),
                ('would_recommend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internship_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='jobs.internshipapplication')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=20)),
                ('years_of_experience', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role_type': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='internshippost',
            index=models.Index(fields=['status', 'start_date'], name='jobs_intern_status_7325ec_idx'),
        ),
        migrations.AddIndex(
            model_name='internshippost',
            index=models.Index(fields=['posted_by'], name='jobs_intern_posted__eb07f7_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipapplication',
            index=models.Index(fields=['student', 'status'], name='jobs_intern_student_c92f01_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipapplication',
            index=models.Index(fields=['internship', 'status'], name='jobs_intern_interns_a4c0bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='internshipapplication',
            unique_together={('internship', 'student')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='jobs_notifi_user_id_c6ad4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentskill',
            unique_together={('student', 'skill_name')},
        ),
    ]
