# Generated by Django 6.0.1 on 2026-01-16 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_adminannouncement_internshipapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHiringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('avg_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('avg_backlogs', models.DecimalField(decimal_places=2, max_digits=4)),
                ('most_common_skills', models.TextField(help_text='Comma separated')),
                ('avg_interview_rounds', models.IntegerField(default=3)),
                ('avg_response_time_days', models.IntegerField(default=7)),
                ('students_hired', models.IntegerField(default=0)),
                ('total_applicants', models.IntegerField(default=1)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, help_text='(hired / applicants) * 100', max_digits=5)),
                ('last_visited_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Historical Hiring Data',
                'ordering': ['-success_rate'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='first_status_change_at',
            field=models.DateTimeField(blank=True, help_text='When first moved from Pending status', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='response_time_hours',
            field=models.IntegerField(blank=True, help_text='Hours from deadline to first update', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status_last_updated_at',
            field=models.DateTimeField(blank=True, help_text='When status was last changed by recruiter', null=True),
        ),
        migrations.CreateModel(
            name='DreamCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('avg_cgpa_required', models.DecimalField(decimal_places=2, default=7.0, max_digits=4)),
                ('common_skills', models.TextField(help_text="Comma separated skills (e.g., 'Python, Django, REST API')")),
                ('typical_interview_rounds', models.IntegerField(default=3)),
                ('typical_feedback_days', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'role_type': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='dream_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dream Companies',
            },
        ),
        migrations.CreateModel(
            name='InterviewExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('round_number', models.IntegerField()),
                ('round_type', models.CharField(choices=[('Online Test', 'Online Test / Assessment'), ('Technical', 'Technical Interview'), ('Coding', 'Coding Round'), ('HR', 'HR Round'), ('Case Study', 'Case Study'), ('Group Discussion', 'Group Discussion'), ('Aptitude', 'Aptitude Test')], max_length=100)),
                ('duration_minutes', models.IntegerField(help_text='How long was the round?')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20)),
                ('questions_asked', models.TextField(help_text='List each question on a new line')),
                ('your_experience', models.TextField(help_text='What did you discuss? What did you solve? Any challenges?')),
                ('tips_for_others', models.TextField(help_text='Advice for future candidates: what to study, what to prepare')),
                ('selected_after', models.BooleanField(help_text='Were you selected/moved to next round after this?')),
                ('status', models.CharField(choices=[('Pending', 'Pending TPO Approval'), ('Approved', 'Approved - Visible to Students'), ('Rejected', 'Rejected by TPO')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.IntegerField(default=0, help_text='How many students viewed this')),
                ('helpful_count', models.IntegerField(default=0, help_text='How many marked as helpful')),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role_type': 'TPO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_experiences', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role_type': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='interview_experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Interview Experiences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrepVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_experiences', models.IntegerField(default=0, help_text='Number of approved interview experiences')),
                ('most_asked_questions', models.TextField(blank=True, help_text='Top 10 questions (JSON array)')),
                ('difficulty_distribution', models.TextField(blank=True, help_text='Easy/Medium/Hard counts (JSON)')),
                ('recommended_topics', models.TextField(blank=True, help_text='Comma separated topics to study')),
                ('avg_interview_rounds', models.IntegerField(default=3)),
                ('avg_selection_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of students selected', max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prep_vault', to='jobs.historicalhiringdata')),
            ],
            options={
                'verbose_name_plural': 'Prep Vaults',
            },
        ),
        migrations.CreateModel(
            name='RecruiterResponseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_response_hours', models.IntegerField(default=0)),
                ('total_jobs_posted', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('responses_given', models.IntegerField(default=0)),
                ('responsiveness_rating', models.DecimalField(decimal_places=1, default=3.0, help_text='1.0 to 5.0 stars', max_digits=2)),
                ('rating_label', models.CharField(default='Average', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('recruiter', models.OneToOneField(limit_choices_to={'role_type': 'RECRUITER'}, on_delete=django.db.models.deletion.CASCADE, related_name='response_rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recruiter Response Ratings',
            },
        ),
    ]
