# Generated by Django 6.0.1 on 2026-01-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_recruiterprofile_block_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Your profile photo', null=True, upload_to='profile_photos/'),
        ),
    ]
