# Generated by Django 6.0.1 on 2026-01-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='block_reason',
            field=models.CharField(blank=True, help_text='Reason for blocking (shows to student)', max_length=500),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='blocked_until',
            field=models.DateTimeField(blank=True, help_text='Cooling period end date (15 days)', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='credit_score',
            field=models.IntegerField(default=100, help_text='Placement Credit Score: 0-100. Starts at 100. Decreases with penalties.'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Blocked from applying due to low PCS (< 50)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pcs_history',
            field=models.TextField(blank=True, help_text='JSON history of all PCS changes'),
        ),
    ]
