# Generated by Django 6.0.1 on 2026-04-20 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(help_text='e.g., Programming, Database, Web Development', max_length=50)),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=20)),
                ('related_skills', models.TextField(blank=True, help_text='Comma separated related skills')),
                ('industry_relevance', models.IntegerField(default=5, help_text='1-10 scale')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySkillDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('skill', models.CharField(max_length=100)),
                ('demand_score', models.IntegerField(default=1, help_text='How much this skill is demanded')),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('Full-time', 'Full-time'), ('Both', 'Both')], default='Both', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('company_name', 'skill', 'job_type')},
            },
        ),
        migrations.CreateModel(
            name='DreamCompanyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream_company', models.CharField(max_length=200)),
                ('current_match_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('required_skills', models.TextField(help_text='JSON list of skills required by dream company')),
                ('skill_gaps', models.TextField(help_text='JSON list of skills student needs to acquire')),
                ('timeline_months', models.IntegerField(help_text='Estimated months to reach required skill level')),
                ('learning_path', models.TextField(blank=True, help_text='JSON structured learning recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role_type': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='dream_company_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('overall_placement', 'Overall Placement Analysis'), ('skill_demand', 'Skill Demand Analysis'), ('student_recommendation', 'Student Recommendations'), ('company_trends', 'Company Trends Analysis')], max_length=50)),
                ('analysis_data', models.TextField(help_text='JSON data containing analysis results')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(limit_choices_to={'role_type': 'TPO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCompanyMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('match_score', models.DecimalField(decimal_places=2, help_text='0-100 match percentage', max_digits=5)),
                ('matching_skills', models.TextField(help_text='JSON list of matching skills')),
                ('missing_skills', models.TextField(blank=True, help_text='JSON list of required but missing skills')),
                ('recommendations', models.TextField(blank=True, help_text='AI recommendations for improvement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role_type': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSkillAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_skills', models.TextField(help_text='JSON list of current skills with proficiency levels')),
                ('skill_gaps', models.TextField(blank=True, help_text='JSON list of skills needed for improvement')),
                ('recommended_companies', models.TextField(blank=True, help_text='JSON list of company matches with scores')),
                ('career_suggestions', models.TextField(blank=True, help_text='AI career path suggestions')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('student', models.ForeignKey(limit_choices_to={'role_type': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='skill_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
